### PR TITLE
Replace ClaimsToken with FundsDistributionToken

### PR DESCRIPTION
**Pull request by jo-es**

### CODE REVIEW

**Comment by Ro5s** [comment]
this looks like a pretty cool implementation // is there a background reference here? We are using this standard for testing purposes: https://github.com/ethereum/EIPs/issues/1843

**Comment by jo-es** [comment]
Sorry for not providing context.
I am one of the author of ERC-1843 and ERC-2222 which this implementation relates to (see: https://github.com/atpar/funds-distribution-token/blob/master/contracts/extensions/FDT_ERC20Extension.sol). We decided to deprecate the ClaimsToken (ERC-1843) approach in favour of the FundsDistributionToken (ERC-2222). FundsDistributionToken supports minting and burning of shares and with that is fully compliant to the security token standard. (https://github.com/ethereum/EIPs/issues/2222)

**Comment by Ro5s** [comment]
awesome! this sounds like a great fit, and very glad to more recent bump. I think down the line it would be neat to add a whitelisting function to allow transfer restrictions to ERC-2222, similar to ERC-1404

**Comment by jo-tud** [comment]
ERC-2222 can be combined with ERC-1404. We designed it to be used as an extension together with other token standards.

**Comment by Ro5s** [comment]
for reference, I will be starting an implementation of erc2222 + erc1404 here: https://github.com/lexDAO/Simple-Restricted-FDT/blob/master/contracts/SimpleRestrictedFDT.sol

**Pull request closed without merging**
